language: node_js

sudo: false

node_js:
  - "10.2.1"

install:
  - yarn

script:
  - yarn build

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://scriptex:$GITHUB_API_KEY@github.com/scriptex/github-pages-vuepress/tree/gh-pages gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
